### ISSUE TITLE
Home route not working

### ISSUE THREAD

**Issue by ZooeyMiller** [FACG2/Diary#36]
I set up a local database with relevant environment variables, built the database, and then ran the project.

When I go to the home route I just get constant loading (indicating that the connection isn't being closed), and an error logged in my terminal:

```
{ Error
    at module.exports (/home/zooey/fac11/Diary/node_modules/jsonwebtoken/verify.js:44:17)
    at home (/home/zooey/fac11/Diary/src/handler.js:16:5)
    at Server.router (/home/zooey/fac11/Diary/src/router.js:24:3)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23) name: 'JsonWebTokenError', message: 'jwt must be provided' }

```

You are not sending a response when you handle the error for the `verify` function, which is why the connection is never closed.

**Comment by ZooeyMiller** [comment]
I think this was actually due to problems with my computer and lingering cookies, when I opened the home route in an incognito tab it worked.
